name: CD
run-name: ${{ inputs.model }} CD
# NOTE: This workflow requires:
# permissions.contents:write
# secrets:inherit with an appropriate GitHub Environment for deployment in the caller
on:
  workflow_call:
    inputs:
      model:
        type: string
        required: true
        description: The model that is being tested and deployed
      root-sbd:
        type: string
        required: false
        # default: The ${{ inputs.model }} above
        description: |
          The name of the root Spack Bundle Definition, if it is different from the model name.
          This is often a package named similarly in ACCESS-NRI/spack-packages.
  # Callers usually have the trigger:
  # push:
  #   branches:
  #     - main
  #     - backport/*.*
  #   paths:
  #     - config/**
  #     - spack.yaml

env:
  SPACK_YAML_MODEL_YQ: .spack.specs[0]
jobs:
  defaults:
    name: Set Defaults
    # Unfortunately, you can't set a dynamic default value based on `inputs` yet
    runs-on: ubuntu-latest
    outputs:
      root-sbd: ${{ steps.root-sbd.outputs.default }}
    steps:
      - name: root-sbd
        id: root-sbd
        run: |
          if [ -z "${{ inputs.root-sbd }}" ]; then
            echo "default=${{ inputs.model }}" >> $GITHUB_OUTPUT
          else
            echo "default=${{ inputs.root-sbd }}" >> $GITHUB_OUTPUT
          fi

  push-tag:
    name: Tag Deployment
    runs-on: ubuntu-latest
    permissions:
      contents: write
    outputs:
      name: ${{ steps.tag.outputs.name }}
    steps:
      - uses: actions/checkout@v4

      - name: Generate Tag
        id: tag
        # Get the tag name from the `spack.yaml` that was merged into main, which
        # is of the form `<model>@git.<version>`.
        run: echo "name=$(yq '${{ env.SPACK_YAML_MODEL_YQ }} | split("@git.") | .[1]' spack.yaml)" >> $GITHUB_OUTPUT

      - name: Push Tag
        # NOTE: Regarding the config user.name/user.email, see https://github.com/actions/checkout/pull/1184
        run: |
          git config user.name ${{ vars.GH_ACTIONS_BOT_GIT_USER_NAME }}
          git config user.email ${{ vars.GH_ACTIONS_BOT_GIT_USER_EMAIL }}
          git tag ${{ steps.tag.outputs.name }} --force
          git push --tags --force

  deploy-release:
    name: Deploy Release
    needs:
      - defaults
      - push-tag
    uses: access-nri/build-cd/.github/workflows/deploy-1-setup.yml@main
    with:
      ref: ${{ github.ref_name }}
      version: ${{ needs.push-tag.outputs.name }}
      root-sbd: ${{ needs.defaults.outputs.root-sbd }}
    secrets: inherit
    permissions:
      contents: write
