name: PR Closed Cleanup
run-name: PR Closed Cleanup
# Remove prereleases that were part of a closed PR, so we save space
# on our deployment targets. If needed, one can still get the
# spack.yaml as part of the closed PR and revive it themselves.

# NOTE: the caller requires the following permissions:
# secrets:inherit
on:
  workflow_call:
    inputs:
      spack-manifest-path:
        type: string
        required: false
        default: spack.yaml
  # Callers usually have the trigger:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  #     - backport/*.*
  #   paths:
  #     - config/**
  #     - spack.yaml
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version-pattern: ${{ steps.version.outputs.pattern }}
      targets: ${{ steps.target.outputs.valid-targets }}
    steps:
      - name: Get data from ${{ github.repository }}
        uses: actions/checkout@v4

      - name: Get Deployment Name
        id: manifest
        uses: access-nri/build-cd/.github/actions/get-spack-manifest@v8
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Get Version Pattern
        id: version
        # For example, `access-om3-pr12-*`
        run: echo "pattern=${{ steps.manifest.outputs.deployment-name }}-pr${{ github.event.pull_request.number }}-*" >> $GITHUB_OUTPUT

      - name: Generate Deployment Target Matrix
        id: target
        uses: access-nri/build-cd/.github/actions/get-target-matrix@v8
        with:
          targets: ${{ vars.PRERELEASE_DEPLOYMENT_TARGETS }}

  undeploy-prereleases:
    name: Undeploy Prereleases Matching ${{ needs.setup.outputs.version-pattern }}
    needs:
      - setup
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.targets) }}
      fail-fast: false
    uses: access-nri/build-cd/.github/workflows/undeploy-1-start.yml@v8
    with:
      version-pattern: ${{ needs.setup.outputs.version-pattern }}
      target: ${{ matrix.target }}
      type: Prerelease
    secrets: inherit
