name: PR Closed Cleanup
run-name: PR Closed Cleanup
# Remove prereleases that were part of a closed PR, so we save space
# on our deployment targets. If needed, one can still get the
# spack.yaml as part of the closed PR and revive it themselves.

# NOTE: the caller requires the following permissions:
# secrets:inherit
on:
  workflow_call:
    inputs:
      spack-manifest-path:
        type: string
        required: false
        default: spack.yaml
  # Callers usually have the trigger:
  # pull_request:
  #   types:
  #     - closed
  #   branches:
  #     - main
  #     - backport/*.*
  #   paths:
  #     - config/**
  #     - spack.yaml
jobs:
  setup:
    name: Setup
    runs-on: ubuntu-latest
    outputs:
      version-pattern: ${{ steps.version.outputs.pattern }}
      targets: ${{ steps.target.outputs.valid-targets }}
    steps:
      - name: Checkout build-cd
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-cd
          ref: ${{ github.workflow_sha }}
          path: _build-cd

      - name: Get data from ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          clean: false

      - name: Get Deployment Name
        id: manifest
        uses: ./_build-cd/.github/actions/get-spack-manifest
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}
        id: version
        # For example, `access-om3-pr12-*`
        run: echo "pattern=${{ steps.manifest.outputs.deployment-name }}-pr${{ github.event.pull_request.number }}-*" >> $GITHUB_OUTPUT

      - name: Generate Deployment Target Matrix
        id: target
        uses: ./_build-cd/.github/actions/get-target-matrix
        with:
          targets: ${{ vars.PRERELEASE_DEPLOYMENT_TARGETS }}

  undeploy-prereleases:
    name: Undeploy ${{ needs.setup.outputs.version-pattern }} from ${{ matrix.target }} Prerelease
    needs:
      - setup
    strategy:
      matrix:
        target: ${{ fromJson(needs.setup.outputs.targets) }}
      fail-fast: false
    runs-on: ubuntu-latest
    environment: ${{ matrix.target }} Prerelease
    steps:
      - name: Checkout build-cd
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-cd
          ref: ${{ github.workflow_sha }}
          path: _build-cd

      - uses: actions/checkout@v6
        with:
          clean: false

      - name: Get Spack Version From config/versions.json
        id: versions
        run: echo "spack=$(jq --compact-output --raw-output '.spack' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Get ${{ matrix.target }} Remote Paths
        id: path
        uses: ./_build-cd/.github/actions/get-deploy-paths
        with:
          spack-installs-root-path: ${{ vars.SPACK_INSTALLS_ROOT_LOCATION }}
          spack-version: ${{ steps.versions.outputs.spack }}
          deployment-target: ${{ matrix.target }}
          deployment-type: Prerelease
          spack-environment: ${{ needs.setup.outputs.version-pattern }}

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Undeploy Environment
        # ssh into deployment environment, create and activate the env, remove all the unneeded environments
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'

          # Enable spack
           module use ${{ vars.ADMIN_MODULES_DIR }}
           module load spack/${{ steps.versions.outputs.spack }}

           envs=$(find ${{ steps.path.outputs.spack }}/../environments -type d -name '${{ needs.setup.outputs.version-pattern }}' -printf '%f ')

          for env in $envs; do
            spack env rm $env --yes-to-all
          done

          # Base scope cleanup (most environments are in this scope)
          spack gc --except-any-environment --keep-build-dependencies --yes-to-all

          # Custom scopes cleanup (like restricted scopes, etc)
          scopes=$(find ${{ steps.path.outputs.spack-config }}/custom/cd -mindepth 1 -maxdepth 1 -type d -printf '%p ')
          for scope in $scopes; do
            spack --config-scope $scope gc --except-any-environment --keep-build-dependencies --yes-to-all
          done
          EOT

      - name: Undeploy Status Notifier
        if: failure()
        run: echo '::error::Deployment ${{ needs.setup.outputs.version-pattern }} could not be removed from ${{ matrix.target }} Prerelease, found at ${{ steps.path.outputs.spack }}. Please check manually.'
