name: Create Deployment Spack
on:
  workflow_dispatch:
    inputs:
      spack-git-url:
        type: string
        required: true
        default: 'https://github.com/access-nri/spack.git'
        description: Git URL for the spack repository
      spack-version:
        type: string
        required: true
        description: A version of spack
      spack-config-version:
        type: string
        required: true
        default: main
        description: A version of ACCESS-NRI/spack-config
      spack-deployment-location:
        type: string
        required: true
        description: |
          A path in the deployment environment where Spack should be created.
          For example, if it is `opt/spack`, spack will be installed under `opt/spack/<spack-version>/`
      module-deployment-location:
        type: string
        required: true
        description: |
          A path in the deployment environment where modules referencing the deployed Spack should be created.
          For example, if it is `opt/modules/spack` for spack v1.1, the modulefile created will be under `opt/modules/spack/1.1`
jobs:
  log-inputs:
    name: Log Inputs
    runs-on: ubuntu-latest
    steps:
      - run: |
          echo '::notice::url = `${{ inputs.spack-git-url }}`, spack version = `${{ inputs.spack-version }}`, spack-config version = `${{ inputs.spack-config-version }}`, deployment location = `${{ inputs.spack-deployment-location }}`, module location = `${{ inputs.module-deployment-location }}`'

  create-spack:
    name: Spack
    runs-on: ubuntu-latest
    # all `secrets` and `vars` inherit from the 'Gadi Spack' GitHub Environment,
    # which can be found in the Settings of the repository.
    environment: "Gadi Spack"
    steps:
      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          hosts: ${{ secrets.SSH_HOST }}
          private-key: ${{ secrets.SSH_KEY }}

      - name: Strip Spack Version
        # FIXME: Need to split a potential -admin section, and access/
        id: strip
        # this step removes the 'release/' part from some spack tags, so our
        # directory structure doesn't contain a 'releases' subdirectory
        run: echo "version=$(echo '${{ inputs.spack-version }}' | cut --delimiter 'v' --fields 2)" >> $GITHUB_OUTPUT

      - name: Install
        id: spack-install
        env:
          ROOT_VERSION_LOCATION: ${{ inputs.spack-deployment-location }}/${{ steps.strip.outputs.version }}
        # This step will fail if `mkdir` fails to create a version directory (e.g. `0.20` is already deployed and exists)
        run: |
          ssh ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          mkdir ${{ env.ROOT_VERSION_LOCATION }} || exit $?
          git -C ${{ env.ROOT_VERSION_LOCATION }} clone ${{ inputs.spack-git-url }} --branch ${{ inputs.spack-version }}
          git -C ${{ env.ROOT_VERSION_LOCATION }} clone https://github.com/ACCESS-NRI/spack-config.git --branch ${{ inputs.spack-config-version }}
          mkdir ${{ env.ROOT_VERSION_LOCATION }}/release
          mkdir ${{ env.ROOT_VERSION_LOCATION }}/logs

          # Create restricted folders
          mkdir -p ${{ env.ROOT_VERSION_LOCATION }}/restricted/ukmo/release
          mkdir -p ${{ env.ROOT_VERSION_LOCATION }}/restricted/ukmo/source_cache
          mkdir -p $TMPDIR/restricted/spack-stage

          setfacl --recursive -m \
            "g:vk83_w:r-X,g:ki32_mosrs:r-X,g:vk83_um:r-X,g:df42:r-X,g::---,o::---,d:g:vk83_w:r-X,d:g:ki32_mosrs:r-X,d:g:vk83_um:r-X,d:g:df42:r-X,d:g::---,d:o::---" \
            ${{ env.ROOT_VERSION_LOCATION }}/restricted $TMPDIR/restricted
          EOT

          . ${{ env.ROOT_VERSION_LOCATION }}/spack/share/spack/setup-env.sh
          spack -d bootstrap now

      - name: Checkout build-cd for modulefiles
        uses: actions/checkout@v6

      - name: Deploy modulefiles
        run: |
          rsync --archive \
            -i ${{ steps.ssh.outputs.private-key-path }} \
            tools/modules/spack/bash_script.sh \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ inputs.module-deployment-location }}/.${{ steps.strip.outputs.version }}.sh

          rsync --archive \
            -i ${{ steps.ssh.outputs.private-key-path }} \
            tools/modules/spack/modulefile \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:${{ inputs.module-deployment-location }}/${{ steps.strip.outputs.version }}

          echo "::notice::Modulefiles for ${{ steps.strip.outputs.version }} deployed. This does not affect the default module."
