name: Deploy
on:
  # This is invoked by both `on.pull_request` and `on.push` events.
  workflow_call:
    inputs:
      deployment-target:
        type: string
        required: true
        description: |
          The target machine for the model being deployed.
          Equivalent to the name of the GitHub Environment, minus a Release/Prerelease Type.
      deployment-type:
        type: string
        required: true
        description: |
          The type of model being deployed.
          Can be one of: Release, Prerelease.
      deployment-version:
        type: string
        required: true
        description: |
          The version of the model being deployed.
          Usually takes the form of either a git tag (2024.12.0), or a Prerelease version (pr12-2)
      deployment-ref:
        type: string
        required: true
        description: |
          The git ref where the spack manifest that will be deployed is located.
          In Prereleases, this is the HEAD of the source branch of the PR.
      prerelease-compare-ref:
        type: string
        required: false
        description: |
          Optional git ref to compare against the current inputs.deployment-ref
          Useful for checking that files have been modified appropriately.
      spack-manifest-path:
        type: string
        required: true
        description: |
          The Spack manifest path relative to the caller repository that will be used for the deployment.
      expected-root-spec-name:
        type: string
        required: true
        description: |
          The expected overarching spack bundle that contains all other packages, set in the caller repository.
          Usually .spack.specs[0] or .spack.definitions.ROOT_PACKAGE in the manifest, but draft PRs can override this.
      spack-manifest-schema-path:
        type: string
        required: true
        description: |
          The path to the Spack manifest schema directory relative to the ACCESS-NRI/schema repository.
      spack-manifest-schema-version:
        type: string
        required: true
        description: |
          The version of the Spack manifest schema to use for validation, from the ACCESS-NRI/schema repository.
      config-versions-schema-version:
        type: string
        required: true
        description: |
          The version of the config/versions.json schema to use for validation, from the ACCESS-NRI/schema repository.
      config-packages-schema-version:
        type: string
        required: true
        description: |
          The version of the config/packages.json schema to use for validation, from the ACCESS-NRI/schema repository.
    outputs:
      general-metadata-artifact-glob:
        value: ${{ jobs.deployment.outputs.general-metadata-artifact-glob }}
        description: |
          General pattern for the artifact that contains the deployment metadata files for this invocation of the job.
          These files are of the form deploy-metadata.{{inputs.deployment-target}}
      general-outputs-artifact-glob:
        value: ${{ jobs.outputs-upload.outputs.general-artifact-name }}
        description: |
          General pattern for the artifact that contains the text outputs for this invocation of the job.
          Output files are of the form deploy-outputs.{{inputs.deployment-target}}
    # TODO: This is a workaround for matrixed dynamic job outputs. See https://github.com/orgs/community/discussions/17245
    # The outputs in the file are below:
    #   model-name:
    #     value: ${{ github.event.repository.name }}
    #     description: |
    #       Name of the model being deployed.
    #   model-deployment-repository:
    #     value: ${{ github.event.repository.html_url }}
    #     description: |
    #       URL of the repository that contains the model being deployed.
    #   model-deployment-repository-spack-manifest-path:
    #     value: ${{ inputs.spack-manifest-path }}
    #     description: |
    #       Path to the spack manifest file in the model deployment repository.
    #   spack-version:
    #     value: ${{ jobs.check-config.outputs.spack-version }}
    #     description: |
    #       Branch of 'access-nri/spack' that is used to deploy the model.
    #       The VERSION part of the 'releases/VERSION' branch.
    #   spack-git-hash:
    #     values: ${{ jobs.check-config.outputs.spack-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/spack' repository at the specified version.
    #   spack-config-version:
    #     value: ${{ jobs.check-config.outputs.spack-config-version }}
    #     description: |
    #       Git ref of 'access-nri/spack-config' that is used to configure spack.
    #   spack-config-git-hash:
    #     value: ${{ jobs.check-config.outputs.spack-config-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/spack-config' repository at the specified version.
    #   builtin-spack-packages-version:
    #     value: ${{ jobs.check-config.outputs.builtin-spack-packages-version }}
    #     description: |
    #       Git ref of 'ACCESS-NRI/upstream-spack-packages' that is used to reference builtin packages in spack.
    #   builtin-spack-packages-git-hash:
    #     value: ${{ jobs.check-config.outputs.builtin-spack-packages-git-hash }}
    #     description: |
    #       Git hash of the 'ACCESS-NRI/upstream-spack-packages' repository at the specified version.
    #   access-spack-packages-version:
    #     value: ${{ jobs.check-config.outputs.access-spack-packages-version }}
    #     description: |
    #       Git ref of 'access-nri/access-spack-packages' that is used to reference custom packages in spack.
    #   access-spack-packages-git-hash:
    #     value: ${{ jobs.check-config.outputs.access-spack-packages-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/access-spack-packages' repository at the specified version.
    #   release-deployment-version:
    #     value: ${{ jobs.check-spack-yaml.outputs.release }}
    #     description: |
    #       Version of the model being deployed as if it were a release version.
    #   ci-configuration-check-failure:
    #     value: ${{ jobs.check-config.outputs.config-settings-failures }}
    #     description: |
    #       Boolean true/false for whether the configuration check failed for inputs.deployment-target
    #   spack-environment-name:
    #     value: ${{ jobs.check-spack-yaml.outputs.spack-env-name }}
    #     description: |
    #       Name for the spack environment that contains the deployed model
    #   root-spec-pkg-hash:
    #     value: ${{ jobs.deployment.outputs.root-spec-pkg-hash }}
    #     description: |
    #       The spack hash of the root spec package that was deployed.
    #   deployment-result:
    #    value: ${{ jobs.deployment.result }}
    #    description: |
    #      Result of the deployment - skipped/cancelled/success/failure
    #   deployment-modules-location:
    #     value: ${{ jobs.deployment.outputs.module-location }}
    #     description: |
    #       Directory containing the modules of the deployed model on the inputs.deployment-target
    #   deployment-spack-location:
    #     value: ${{ jobs.deployment.outputs.spack-location }}
    #     description: |
    #       Directory containing the spack instance of the deployed model on the inputs.deployment-target
jobs:
  check-config:
    name: '${{ inputs.deployment-target }}: Check Config'
    runs-on: ubuntu-latest
    # A lot of outputs, versions for repositories are taken from different sources:
    #   Taken from central build-cd config/settings.json: spack (SHA), spack-config, builtin spack-packages
    #   Taken from caller config/versions.json: spack (branch), access-spack-packages
    env:
      # Paths prepended with actions/checkout path argument
      mdr-config-versions-json-path: model/config/versions.json
      mdr-config-packages-json-path: model/config/packages.json
      build-cd-config-settings-json-path: latest-build-cd/config/settings.json
    outputs:
      spack-version: ${{ steps.config-versions-refs.outputs.spack-branch }}
      spack-git-hash: ${{ steps.spack-sha.outputs.sha }}

      builtin-spack-packages-version: ${{ steps.builtin-spack-packages.outputs.ref }}
      builtin-spack-packages-git-hash: ${{ steps.builtin-spack-packages-sha.outputs.sha }}

      access-spack-packages-version: ${{ steps.config-versions-refs.outputs.access-spack-packages-ref }}
      access-spack-packages-git-hash: ${{ steps.access-spack-packages-sha.outputs.sha }}

      spack-config-version:  ${{ steps.config-settings-refs.outputs.spack-config-ref }}
      spack-config-git-hash: ${{ steps.spack-config-sha.outputs.sha }}

      config-settings-failures: ${{ steps.settings.outputs.failures }}
    steps:
      # Validate the caller repository's config files and versions
      - name: '${{ github.repository }}: Checkout ${{ github.repository }} Config'
        uses: actions/checkout@v6
        with:
          path: model
          ref: ${{ inputs.deployment-ref }}

      - name: '${{ github.repository }}: Validate config/versions.json'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.config-versions-schema-version }}
          schema-location: au.org.access-nri/model/deployment/config/versions
          data-location: ${{ env.mdr-config-versions-json-path }}

      - name: '${{ github.repository }}: Validate config/packages.json'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.config-packages-schema-version }}
          schema-location: au.org.access-nri/model/deployment/config/packages
          data-location: ${{ env.mdr-config-packages-json-path }}

      - name: '${{ github.repository }}: Get repository refs from config/versions.json'
        id: config-versions-refs
        run: |
          echo "spack-branch=$(jq --compact-output --raw-output '.spack' ${{ env.mdr-config-versions-json-path}})" >> $GITHUB_OUTPUT
          echo "access-spack-packages-ref=$(jq --compact-output --raw-output '."access-spack-packages"' ${{ env.mdr-config-versions-json-path }})" >> $GITHUB_OUTPUT

      - name: '${{ github.repository }}: Validate spack branch'
        id: spack-branch-check
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack
          ref: releases/v${{ steps.config-versions-refs.outputs.spack-branch }}

      - name: '${{ github.repository }}: Get access-spack-packages SHA'
        id: access-spack-packages-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/access-spack-packages
          ref: ${{ steps.config-versions-refs.outputs.access-spack-packages-ref }}

      # Validate the build-cd repository's config/settings.json for the deployment target
      - name: 'build-cd: Checkout Current build-cd Config'
        uses: actions/checkout@v6
        # This checkout is to get the current HEAD of build-cd to get
        # the most up-to-date settings.json for validation
        with:
          repository: access-nri/build-cd
          path: latest-build-cd

      - name: 'build-cd: Checkout build-cd for custom action'
        # This checkout is used to call the next steps custom action, at
        # the same commit the workflow is running.
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-cd
          ref: ${{ job.workflow_sha }}
          path: build-cd

      - name: 'build-cd: Validate config/settings.json'
        id: settings
        uses: ./build-cd/.github/actions/validate-deployment-settings
        with:
          settings-path: ${{ env.build-cd-config-settings-json-path }}
          target: ${{ inputs.deployment-target }}

      - name: 'build-cd: Get repository refs from config/settings.json'
        id: config-settings-refs
        run: |
          refs_for_deployment=$(jq \
              --arg spack_version "${{ steps.config-versions-refs.outputs.spack-branch }}" \
              '.deployment.${{ inputs.deployment-target }}.${{ inputs.deployment-type }}[$spack_version]' \
              ${{ env.build-cd-config-settings-json-path }}
          )

          echo "$refs_for_deployment"

          echo "spack-ref=$(jq --compact-output --raw-output '.spack' <<< "$refs_for_deployment")" >> $GITHUB_OUTPUT
          echo "spack-config-ref=$(jq --compact-output --raw-output '."spack-config"' <<< "$refs_for_deployment")" >> $GITHUB_OUTPUT

      - name: 'build-cd: Checkout spack-config to get builtin spack-packages ref'
        uses: actions/checkout@v6
        with:
          repository: ACCESS-NRI/spack-config
          ref: ${{ steps.config-settings-refs.outputs.spack-config-ref }}
          path: spack-config

      - name: 'build-cd: Get builtin spack-packages ref'
        id: builtin-spack-packages
        run: |
          echo "ref=$(yq '.repos | .builtin // ."builtin:" | .branch // .tag // .commit' spack-config/v${{ steps.config-versions-refs.outputs.spack-branch }}/repos.yaml)" >> $GITHUB_OUTPUT

      - name: 'build-cd: Get spack SHA'
        id: spack-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack
          ref: ${{ steps.config-settings-refs.outputs.spack-ref }}

      - name: 'build-cd: Get spack-config SHA'
        id: spack-config-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack-config
          ref: ${{ steps.config-settings-refs.outputs.spack-config-ref }}

      - name: 'build-cd: Get builtin spack-packages SHA'
        id: builtin-spack-packages-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/upstream-spack-packages
          ref: ${{ steps.builtin-spack-packages.outputs.ref }}

  check-spack-yaml:
    name: '${{ inputs.deployment-target }}: Check Spack Manifest'
    runs-on: ubuntu-latest
    env:
      # Note: since this is a string representation of a boolean, it must be compared as a string.
      # Yes, github.event.issue.draft refers to the pull request if the comment is made on a pull request!
      IS_NOT_DRAFT: ${{ (github.event_name == 'pull_request' && !github.event.pull_request.draft) || (github.event_name == 'issue_comment' && !github.event.issue.draft) }}
    permissions:
      pull-requests: write
    outputs:
      # Release version of the deployment. Inferred if not given in inputs.deployment-version
      release: ${{ steps.current.outputs.deployment-version }}
      # Spack env name in form <model>-<version>
      spack-env-name: ${{ steps.get-env-name.outputs.env-name }}
    steps:
      - uses: actions/checkout@v6
        with:
          fetch-depth: 0
          ref: ${{ inputs.deployment-ref }}

      - name: Checkout build-cd
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-cd
          ref: ${{ job.workflow_sha }}
          path: build-cd

      - name: Validate ACCESS-NRI spack manifest restrictions
        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.spack-manifest-schema-version }}
          schema-location: ${{ inputs.spack-manifest-schema-path }}
          data-location: ${{ inputs.spack-manifest-path }}

      - name: Get current (${{ inputs.deployment-ref }}) root spec version
        id: current
        uses: ./build-cd/.github/actions/get-spack-manifest
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Disallow multi-spec Releases
        if: inputs.deployment-type == 'Release'
        # FIXME: Once the necessary infrastructure/guidance is in place, remove this step. See ACCESS-NRI/build-cd#344
        run: |
          root_specs=$(yq '.spack.specs | select(.[] == "${{ steps.current.outputs.deployment-name }}*") | length' ${{ inputs.spack-manifest-path }})

          if [ "$root_specs" -gt 1 ]; then
            echo "::error::We don't yet support multiple root specs with the same package name. Contact the Model Release Team for information."
            exit 1
          fi

      - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
        if: inputs.deployment-type != 'Release'
        continue-on-error: true
        id: checkout-base-spack
        run: |
          git checkout ${{ inputs.prerelease-compare-ref }}

          if [ ! -f ${{ inputs.spack-manifest-path }} ]; then
              echo "::notice::There is no previous version of ${{ inputs.spack-manifest-path }} to check at ${{ inputs.prerelease-compare-ref }}, continuing..."
              exit 1
          fi

          # If the first commit in the repository is the template, there won't be anything defined in the speclist
          # So we should skip checking the version!
          if ! yq --exit-status '.spack.specs' ${{ inputs.spack-manifest-path }}; then
            echo "::notice::${{ inputs.spack-manifest-path }} at ${{ inputs.prerelease-compare-ref }} is a template, continuing..."
            exit 1
          fi

      - name: Get base root spec version
        id: base
        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure'
        uses: ./build-cd/.github/actions/get-spack-manifest
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Check Model Version Modified
        # We don't want to fire off model deployment version checks if the PR is never going to be merged.
        # We determine this by checking if either the pull request, or the pull request that a comment
        # belongs to, is drafted.
        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure' && env.IS_NOT_DRAFT == 'true'
        id: version-modified
        run: |
          if [[ "${{ steps.base.outputs.deployment-version }}" == "${{ steps.current.outputs.deployment-version }}" ]]; then
              echo "::warning::The version string in ${{ inputs.spack-manifest-path }} hasn't been modified in this PR, but needs to be before merging."
              exit 1
          fi

      - name: Same Model Version Failure Notifier
        if: failure() && steps.version-modified.outcome == 'failure'
        # TODO: We don't yet support bumping files outside of ./spack.yaml, so this is a temporary solution.
        env:
          BUMP_COMMENT_BODY: |-
            Alternatively, comment the following to have it updated and committed automatically:
              * `!bump major` for feature releases
              * `!bump minor` for bugfixes
        uses: access-nri/actions/.github/actions/pr-comment@main
        with:
          comment: |
              The model version in the `${{ inputs.spack-manifest-path }}` has not been updated.
              You can update it manually.
              ${{ inputs.spack-manifest-path != './spack.yaml' && env.BUMP_COMMENT_BODY || '' }}

      - name: Set Spack Env Name String
        id: get-env-name
        # replace occurences of '.' with '_' in environment name as spack doesn't support '.'. Ex: 'access-om2-v1.0.0' -> 'access-om2-v1_0_0'.
        run: echo "env-name=$(echo '${{ inputs.expected-root-spec-name }}-${{ inputs.deployment-version }}' | tr '.' '_')" >> $GITHUB_OUTPUT

  deployment:
    name: '${{ inputs.deployment-target }}: Deployment'
    needs:
      - check-config  # Verify configuration information is correct
      - check-spack-yaml  # Verify spack manifest information is correct
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
    env:
      METADATA_PATH: /opt/metadata
      ARTIFACT_NAME: deploy-${{ inputs.expected-root-spec-name }}-metadata.${{ inputs.deployment-target }}
    outputs:
      spack-location: ${{ steps.location.outputs.spack }}
      modules-location: ${{ steps.location.outputs.modules }}
      root-spec-pkg-hash: ${{ steps.metadata.outputs.root-spec-pkg-hash }}
      general-metadata-artifact-glob: ${{ env.ARTIFACT_NAME }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v6
        with:
          ref: ${{ inputs.deployment-ref }}

      - name: Checkout build-cd
        uses: actions/checkout@v6
        with:
          repository: access-nri/build-cd
          ref: ${{ job.workflow_sha }}
          path: build-cd

      - name: Get Scopes From config/versions.json
        id: custom-scopes
        run: |
          echo "space-separated=$(jq --compact-output --raw-output '."custom-scopes" // [] | join(" ")' ./config/versions.json)" >> $GITHUB_OUTPUT
          echo "comma-separated=$(jq --compact-output --raw-output '."custom-scopes" // [] | join(",")' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Get ${{ inputs.deployment-target }} ${{ inputs.deployment-type }} Remote Paths
        id: path
        uses: ./build-cd/.github/actions/get-deploy-paths
        with:
          spack-installs-root-path: ${{ vars.SPACK_INSTALLS_ROOT_LOCATION }}
          spack-version: ${{ needs.check-config.outputs.spack-version }}
          deployment-target: ${{ inputs.deployment-target }}
          deployment-type: ${{ inputs.deployment-type }}
          spack-environment: ${{ needs.check-spack-yaml.outputs.spack-env-name }}

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Setup Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Injection Requirements
        working-directory: build-cd
        run: python -m pip install -r scripts/spack_manifest/injection/requirements.txt

      - name: Spack Manifest - Get Provenance and Injection Packages
        id: config-packages
        run: |
          packages_for_injection=$(jq -cr '.provenance + .injection | join(",")' config/packages.json)
          packages_for_provenance=$(jq -cr '.provenance | join(",")' config/packages.json)

          echo "Packages to be injected: $packages_for_injection"
          echo "Packages for provenance: $packages_for_provenance"

          echo "packages-for-injection=$packages_for_injection" >> $GITHUB_OUTPUT
          echo "packages-for-provenance=$packages_for_provenance" >> $GITHUB_OUTPUT

      - name: Spack Manifest - Modules Injection
        # Injects relevant module projections and includes into the spack manifest so users don't have to
        working-directory: build-cd
        run: |
          python -m scripts.spack_manifest.injection.modules \
            --manifest ../${{ inputs.spack-manifest-path }} \
            --packages "${{ steps.config-packages.outputs.packages-for-injection }}" \
            --output ../${{ inputs.spack-manifest-path }}

      - name: Spack Manifest - Prerelease Injection
        if: inputs.deployment-type == 'Prerelease'
        # Modifies the name of the prerelease modulefile to the pr<number>-<deployment number>` style.
        # Also adds a repos section that points to the prereleases specific access-spack-packages repo.
        working-directory: build-cd
        run: |
          python -m scripts.spack_manifest.injection.prerelease \
            --manifest ../${{ inputs.spack-manifest-path }} \
            --version ${{ inputs.deployment-version }} \
            --spack-packages-path ${{ steps.path.outputs.spack-environment }}/access-spack-packages \
            --spack-packages-version-sha ${{ needs.check-config.outputs.access-spack-packages-git-hash }} \
            --output ../${{ inputs.spack-manifest-path }}

      - name: Copy ${{ inputs.spack-manifest-path }}
        run: |
          # TODO: Remove once we have enough failing IP addresses for NCI HELP-209915
          curl ifconfig.me

          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ inputs.spack-manifest-path }} \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_YAML_LOCATION }}/${{ inputs.expected-root-spec-name }}-${{ github.run_id }}.spack.yaml

      - name: Fetch git sources for packages to build
        # Workaround for ACCESS-NRI/spack#2.
        # TODO: Remove once underlying spack issue is fixed
        run: |
          # TODO: Remove once we have enough failing IP addresses for NCI HELP-209915
          curl ifconfig.me

          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'

          if [ ! -d "${{ steps.path.outputs.root }}/spack-admin-cache/git_repos" ]; then
            echo "::warning::Unable to find git_repos folder under ${{ steps.path.outputs.root }} - spack will attempt fetch instead"
            exit 0
          fi

          cd "${{ steps.path.outputs.root }}/spack-admin-cache/git_repos" || exit 0

          for package_repo in *; do
            git -C "./$package_repo" fetch --verbose --update-head-ok origin "+refs/heads/*:refs/heads/*"
          done
          EOT

      - name: Set spack-config scopes path
        id: spack-config-scopes
        run: |
          deployment_target="${{ inputs.deployment-target }}"
          lowered_deployment_target="${deployment_target,,}"
          deployment_path="${{ steps.path.outputs.spack-config }}/custom/cd/v${{ needs.check-config.outputs.spack-version }}/${lowered_deployment_target}"

          echo "$deployment_path"

          echo "path=$deployment_path" >> $GITHUB_OUTPUT

      - name: Deploy to ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
        id: deploy
        env:
          SCOPES: ${{ steps.custom-scopes.outputs.space-separated }}
        # ssh into deployment environment, create and activate the env, install the spack manifest.
        run: |
          # TODO: Remove once we have enough failing IP addresses for NCI HELP-209915
          curl ifconfig.me

          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Check that a suitable deployment location exists
          if [ ! -d "${{ steps.path.outputs.root }}" ]; then
            echo '::error::A deployment of spack does not exist in ${{ steps.path.outputs.root }} for ${{ inputs.deployment-target }} ${{ inputs.deployment-type}}'
            exit 1
          fi

          # Enable spack
          module use ${{ vars.ADMIN_MODULES_DIR }}
          module load spack/${{ needs.check-config.outputs.spack-version }}

          # Create and activate environment
          spack env activate ${{ needs.check-spack-yaml.outputs.spack-env-name }} --create --envfile ${{ vars.SPACK_YAML_LOCATION }}/${{ inputs.expected-root-spec-name }}-${{ github.run_id }}.spack.yaml

          # Update access-spack-packages repository before installation
          spack repo set access_spack_packages
          spack repo update access_spack_packages --commit ${{ needs.check-config.outputs.access-spack-packages-git-hash }}

          # Finally, install the spack manifest
          spack --debug \
            $(for s in ${{ env.SCOPES }}; do echo -n "--config-scope=${{ steps.spack-config-scopes.outputs.path }}/$s "; done) \
            install --fail-fast --fresh ${{ vars.SPACK_INSTALL_ADDITIONAL_ARGS }} || exit $?

          spack \
            $(for s in ${{ env.SCOPES }}; do echo -n "--config-scope=${{ steps.spack-config-scopes.outputs.path }}/$s "; done) \
            module tcl refresh --upstream-modules -y
          EOT

      - name: Move spack logs
        if: always() && (steps.deploy.outcome == 'success' || steps.deploy.outcome == 'failure')
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          find . -maxdepth 1 -regex './spack-cc-.+' -exec mv {} ${{ steps.path.outputs.root }}/logs \;
          EOT

      - name: Export deployment target locations
        id: location
        run: |
          echo "spack=${{ steps.path.outputs.spack }}" >> $GITHUB_OUTPUT
          echo "modules=${{ vars.DEPLOYED_MODULES_DIR }}" >> $GITHUB_OUTPUT

      - name: Get metadata from ${{ inputs.deployment-target }} ${{ inputs.deployment-type}}
        id: metadata
        if: inputs.deployment-type == 'Release'
        # Get the metadata from the spack environment regarding build database packages
        run: |
          rsync --perms -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            build-cd/scripts/release_provenance/get_data_from_deployment.py \
            ${{ secrets.USER }}@${{ secrets.HOST }}:${{ steps.path.outputs.spack-environment }}/

          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'

          # Enable spack
          module use ${{ vars.ADMIN_MODULES_DIR }}
          module load spack/${{ needs.check-config.outputs.spack-version }}

          ${{ steps.path.outputs.spack-environment }}/get_data_from_deployment.py \
            --environment ${{ steps.path.outputs.spack-environment }} \
            --deployment-name ${{ inputs.expected-root-spec-name }} \
            --packages "${{ steps.config-packages.outputs.packages-for-provenance }}" \
            --config-scopes-base-dir "${{ steps.spack-config-scopes.outputs.path }}" \
            --config-scopes "${{ steps.custom-scopes.outputs.comma-separated }}" \
            --output ${{ steps.path.outputs.spack-environment }}
          EOT

          # Output root spec package hash from ssh session
          echo "root-spec-pkg-hash=$(\
            ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} \
              'cat ${{ steps.path.outputs.spack-environment }}/root-spec-pkg-hash.txt' \
          )" >> $GITHUB_OUTPUT

      - name: Tar spack environment metadata
        # We want to attempt to tar up the .spack-env directory even if the install fails, so we can save inodes.
        if: always() && (steps.deploy.conclusion == 'success' || steps.deploy.conclusion == 'failure')
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          if [ -d "${{ steps.path.outputs.spack-environment }}/.spack-env" ]; then
            tar --remove-files --create --file ${{ steps.path.outputs.spack-environment }}/.spack-env.tar ${{ steps.path.outputs.spack-environment }}/.spack-env
          else
            echo "::warning::No .spack-env directory found in ${{ steps.path.outputs.spack-environment }}, not tarring. There may be an issue with the environment."
          fi
          EOT

      # Release
      - name: Get Release Metadata
        # Copy both the spack.* files and the build-db-pkgs.json file (for Release) to the artifact
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            '${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ steps.path.outputs.spack-environment }}/spack.*' \
            ./${{ env.ARTIFACT_NAME }}

          if [[ "${{ inputs.deployment-type }}" == "Release" ]]; then
            rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
              '${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json' \
              ./${{ env.ARTIFACT_NAME }}
          fi

          # Rename the files to include the deployment environment
          cd ./${{ env.ARTIFACT_NAME }}
          for file in *; do
            mv "$file" "${{ inputs.deployment-target }}.$file"
          done
          cd -

      - name: Upload Metadata Artifact
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_NAME }}/*

  outputs-upload:
    name: '${{ inputs.deployment-target }}:Outputs Upload'
    # Creates a JSON artifact with information on the deployment created during this run.
    # In workflows that call this as a matrix, one must do a deep merge with all files generated from the matrix,
    # using the outputs.general-outputs-artifact-name artifact as part of the workflow run.
    if: always()
    # always, because we might want to interrogate some of the information even in a failed deployment.
    needs:
      - check-config
      - check-spack-yaml
      - deployment
    runs-on: ubuntu-latest
    env:
      UPLOAD_FILE_NAME: deploy-${{ inputs.expected-root-spec-name }}-outputs.${{ inputs.deployment-target }}
    outputs:
      general-artifact-name: deploy-${{ inputs.expected-root-spec-name }}-outputs.*
    steps:
      - name: Create outputs file
        # See the on.workflow_call.outputs section for details on the info created.
        run: |
          jq --null-input '{
            model_name: "${{ github.event.repository.name }}",
            model_deployment_repository: "${{ github.event.repository.html_url }}",
            model_deployment_repository_spack_manifest_path: "${{ inputs.spack-manifest-path }}",
            spack_version: "${{ needs.check-config.outputs.spack-version }}",
            spack_git_hash: "${{ needs.check-config.outputs.spack-git-hash }}",
            spack_config_version: "${{ needs.check-config.outputs.spack-config-version }}",
            spack_config_git_hash: "${{ needs.check-config.outputs.spack-config-git-hash }}",
            builtin_spack_packages_version: "${{ needs.check-config.outputs.builtin-spack-packages-version }}",
            builtin_spack_packages_git_hash: "${{ needs.check-config.outputs.builtin-spack-packages-git-hash }}",
            access_spack_packages_version: "${{ needs.check-config.outputs.access-spack-packages-version }}",
            access_spack_packages_git_hash: "${{ needs.check-config.outputs.access-spack-packages-git-hash }}",
            ci_configuration_check_failure: ${{ needs.check-config.outputs.config-settings-failures != '' }},
            release_deployment_version: "${{ needs.check-spack-yaml.outputs.release }}",
            spack_environment_name: "${{ needs.check-spack-yaml.outputs.spack-env-name }}",
            root_spec_pkg_hash: "${{ needs.deployment.outputs.root-spec-pkg-hash }}",
            deployment_result: "${{ needs.deployment.result }}",
            deployment_modules_location: "${{ needs.deployment.outputs.modules-location }}",
            deployment_spack_location: "${{ needs.deployment.outputs.spack-location }}"
          }' > ./${{ env.UPLOAD_FILE_NAME }}

      - name: Upload
        uses: actions/upload-artifact@v7
        with:
          name: ${{ env.UPLOAD_FILE_NAME }}
          path: ./${{ env.UPLOAD_FILE_NAME }}
          if-no-files-found: error
