name: Deployment Setup
on:
  workflow_call:
    inputs:
      type:
        type: string
        required: false
        default: release
        description: The type of deployment - either 'release' or 'prerelease'
      ref:
        type: string
        required: true
        description: The git commit-ish ref where the `spack.yaml` is located
      version:
        type: string
        required: true
        description: The version for the model being deployed
      root-sbd:
        type: string
        required: false
        # default: The model name, taken from the callers repository name
        description: The root SBD that is being used as the modulefile name

jobs:
  setup-spack-env:
    name: Setup Spack Environment
    runs-on: ubuntu-latest
    outputs:
      # Model name inferred from repository name
      model: ${{ steps.get-model.outputs.model }}
      # Spack env name in form <model>-<version>
      env-name: ${{ steps.get-env-name.outputs.env-name }}
      # Root SBD that defaults to the model name
      root-sbd: ${{ steps.set-root-sbd.outputs.root-sbd }}
    steps:
      - name: Get Model
        id: get-model
        # for the cases where the repo name is in uppercase but the package name is lowercase (eg. access-nri/MOM5)
        run: echo "model=$(echo ${{ github.event.repository.name }} | tr [:upper:] [:lower:])" >> $GITHUB_OUTPUT

      - name: Set Spack Env Name String
        id: get-env-name
        # replace occurences of '.' with '_' in environment name as spack doesn't support '.'. Ex: 'access-om2-v1.0.0' -> 'access-om2-v1_0_0'.
        run: echo "env-name=$(echo '${{ steps.get-model.outputs.model }}-${{ inputs.version }}' | tr '.' '_')" >> $GITHUB_OUTPUT

      - name: Set Root SBD Default
        id: set-root-sbd
        # We set the default here because we don't have access to the modified repo name in the inputs section yet
        run: |
          if [[ "${{ inputs.root-sbd }}" == "" ]]; then
            echo "root-sbd=${{ steps.get-model.outputs.model }}" >> $GITHUB_OUTPUT
          else
            echo "root-sbd=${{ inputs.root-sbd }}" >> $GITHUB_OUTPUT
          fi

  setup-deployment-env:
    name: Setup Deployment Environment
    runs-on: ubuntu-latest
    outputs:
      deployment-environments: ${{ steps.get-deployment-environment.outputs.deployment-environments }}
    steps:
      - name: Checkout Config
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd

      - name: Get Environments
        id: get-deployment-environment
        run: |
          if [[ "${{ inputs.type }}" == "release" ]]; then
            echo "deployment-environments=$(jq --compact-output '.environments' ./config/deployment-environment.json)" >> $GITHUB_OUTPUT
          elif [[ "${{ inputs.type }}" == "prerelease" ]]; then
            echo "deployment-environments=$(jq --compact-output '."prerelease-environments"' ./config/deployment-environment.json)" >> $GITHUB_OUTPUT
          else
            echo "::error::The 'type' input was invalid. Check the inputs documentation."
            exit 1
          fi

  deployment:
    name: Deployment
    needs:
      - setup-spack-env
      - setup-deployment-env
    strategy:
      fail-fast: false
      matrix:
        deployment-environment: ${{ fromJson(needs.setup-deployment-env.outputs.deployment-environments) }}
    uses: access-nri/build-cd/.github/workflows/deploy-2-start.yml@main
    with:
      type: ${{ inputs.type }}
      model: ${{ needs.setup-spack-env.outputs.model }}
      ref: ${{ inputs.ref }}
      version: ${{ inputs.version }}
      env-name: ${{ needs.setup-spack-env.outputs.env-name }}
      deployment-environment: ${{ matrix.deployment-environment }}
      root-sbd: ${{ needs.setup-spack-env.outputs.root-sbd }}
    secrets: inherit
