name: Deploy
on:
  # This is invoked by both `on.pull_request` and `on.push` events.
  workflow_call:
    inputs:
      deployment-target:
        type: string
        required: true
        description: |
          The target machine for the model being deployed.
          Equivalent to the name of the GitHub Environment, minus a Release/Prerelease Type.
      deployment-type:
        type: string
        required: true
        description: |
          The type of model being deployed.
          Can be one of: Release, Prerelease.
      deployment-version:
        type: string
        required: true
        description: |
          The version of the model being deployed.
          Usually takes the form of either a git tag (2024.12.0), or a Prerelease version (pr12-2)
      deployment-ref:
        type: string
        required: true
        description: |
          The git ref where the spack manifest that will be deployed is located.
          In Prereleases, this is the HEAD of the source branch of the PR.
      prerelease-compare-ref:
        type: string
        required: false
        description: |
          Optional git ref to compare against the current inputs.deployment-ref
          Useful for checking that files have been modified appropriately.
      spack-manifest-path:
        type: string
        required: true
        description: |
          The Spack manifest path relative to the caller repository that will be used for the deployment.
      expected-root-spec-name:
        type: string
        required: true
        description: |
          The expected overarching spack bundle that contains all other packages, set in the caller repository.
          Usually .spack.specs[0] or .spack.definitions.ROOT_PACKAGE in the manifest, but draft PRs can override this.
      spack-manifest-schema-path:
        type: string
        required: true
        description: |
          The path to the Spack manifest schema directory relative to the ACCESS-NRI/schema repository.
      spack-manifest-schema-version:
        type: string
        required: true
        description: |
          The version of the Spack manifest schema to use for validation, from the ACCESS-NRI/schema repository.
      config-versions-schema-version:
        type: string
        required: true
        description: |
          The version of the config/versions.json schema to use for validation, from the ACCESS-NRI/schema repository.
      config-packages-schema-version:
        type: string
        required: true
        description: |
          The version of the config/packages.json schema to use for validation, from the ACCESS-NRI/schema repository.
    outputs:
      general-metadata-artifact-glob:
        value: ${{ jobs.deployment.outputs.general-metadata-artifact-glob }}
        description: |
          General pattern for the artifact that contains the deployment metadata files for this invocation of the job.
          These files are of the form deploy-metadata.{{inputs.deployment-target}}
      general-outputs-artifact-glob:
        value: ${{ jobs.outputs-upload.outputs.general-artifact-name }}
        description: |
          General pattern for the artifact that contains the text outputs for this invocation of the job.
          Output files are of the form deploy-outputs.{{inputs.deployment-target}}
    # TODO: This is a workaround for matrixed dynamic job outputs. See https://github.com/orgs/community/discussions/17245
    # The outputs in the file are below:
    #   model-name:
    #     value: ${{ github.event.repository.name }}
    #     description: |
    #       Name of the model being deployed.
    #   model-deployment-repository:
    #     value: ${{ github.event.repository.html_url }}
    #     description: |
    #       URL of the repository that contains the model being deployed.
    #   model-deployment-repository-spack-manifest-path:
    #     value: ${{ inputs.spack-manifest-path }}
    #     description: |
    #       Path to the spack manifest file in the model deployment repository.
    #   spack-version:
    #     value: ${{ jobs.check-config.outputs.spack-version }}
    #     description: |
    #       Branch of 'access-nri/spack' that is used to deploy the model.
    #       The VERSION part of the 'releases/VERSION' branch.
    #   spack-git-hash:
    #     values: ${{ jobs.check-config.outputs.spack-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/spack' repository at the specified version.
    #   spack-config-version:
    #     value: ${{ jobs.check-config.outputs.spack-config-version }}
    #     description: |
    #       Git ref of 'access-nri/spack-config' that is used to configure spack.
    #   spack-config-git-hash:
    #     value: ${{ jobs.check-config.outputs.spack-config-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/spack-config' repository at the specified version.
    #   builtin-spack-packages-version:
    #     value: ${{ jobs.check-config.outputs.builtin-spack-packages-version }}
    #     description: |
    #       Git ref of 'spack/spack-packages' that is used to reference builtin packages in spack.
    #   builtin-spack-packages-git-hash:
    #     value: ${{ jobs.check-config.outputs.builtin-spack-packages-git-hash }}
    #     description: |
    #       Git hash of the 'spack/spack-packages' repository at the specified version.
    #   access-spack-packages-version:
    #     value: ${{ jobs.check-config.outputs.access-spack-packages-version }}
    #     description: |
    #       Git ref of 'access-nri/access-spack-packages' that is used to reference custom packages in spack.
    #   access-spack-packages-git-hash:
    #     value: ${{ jobs.check-config.outputs.access-spack-packages-git-hash }}
    #     description: |
    #       Git hash of the 'access-nri/access-spack-packages' repository at the specified version.
    #   release-deployment-version:
    #     value: ${{ jobs.check-spack-yaml.outputs.release }}
    #     description: |
    #       Version of the model being deployed as if it were a release version.
    #   ci-configuration-check-failure:
    #     value: ${{ jobs.check-config.outputs.config-settings-failures }}
    #     description: |
    #       Boolean true/false for whether the configuration check failed for inputs.deployment-target
    #   spack-environment-name:
    #     value: ${{ jobs.check-spack-yaml.outputs.spack-env-name }}
    #     description: |
    #       Name for the spack environment that contains the deployed model
    #   root-spec-pkg-hash:
    #     value: ${{ jobs.deployment.outputs.root-spec-pkg-hash }}
    #     description: |
    #       The spack hash of the root spec package that was deployed.
    #   deployment-result:
    #    value: ${{ jobs.deployment.result }}
    #    description: |
    #      Result of the deployment - skipped/cancelled/success/failure
    #   deployment-modules-location:
    #     value: ${{ jobs.deployment.outputs.module-location }}
    #     description: |
    #       Directory containing the modules of the deployed model on the inputs.deployment-target
    #   deployment-spack-location:
    #     value: ${{ jobs.deployment.outputs.spack-location }}
    #     description: |
    #       Directory containing the spack instance of the deployed model on the inputs.deployment-target
jobs:
  check-config:
    name: '${{ inputs.deployment-target }}: Check Config'
    runs-on: ubuntu-latest
    # A lot of outputs, versions for repositories are taken from different sources:
    #   Taken from central build-cd config/settings.json: spack (SHA), spack-config, builtin spack-packages
    #   Taken from caller config/versions.json: spack (branch), access-spack-packages
    env:
      # Paths prepended with actions/checkout path argument
      mdr-config-versions-json-path: model/config/versions.json
      mdr-config-packages-json-path: model/config/packages.json
      build-cd-config-settings-json-path: build-cd/config/settings.json
    outputs:
      spack-version: ${{ steps.config-versions-refs.outputs.spack-branch }}
      spack-git-hash: ${{ steps.spack-sha.outputs.sha }}

      builtin-spack-packages-version: ${{ steps.config-settings-refs.outputs.builtin-spack-packages-ref }}
      builtin-spack-packages-git-hash: ${{ steps.builtin-spack-packages-sha.outputs.sha }}

      access-spack-packages-version: ${{ steps.config-versions-refs.outputs.access-spack-packages-ref }}
      access-spack-packages-git-hash: ${{ steps.access-spack-packages-sha.outputs.sha }}

      spack-config-version:  ${{ steps.config-settings-refs.outputs.spack-config-ref }}
      spack-config-git-hash: ${{ steps.spack-config-sha.outputs.sha }}

      config-settings-failures: ${{ steps.settings.outputs.failures }}
    steps:
      # Validate the caller repository's config files and versions
      - name: '${{ github.repository }}: Checkout ${{ github.repository }} Config'
        uses: actions/checkout@v4
        with:
          path: model
          ref: ${{ inputs.deployment-ref }}

      - name: '${{ github.repository }}: Validate config/versions.json'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.config-versions-schema-version }}
          schema-location: au.org.access-nri/model/deployment/config/versions
          data-location: ${{ env.mdr-config-versions-json-path }}

      - name: '${{ github.repository }}: Validate config/packages.json'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.config-packages-schema-version }}
          schema-location: au.org.access-nri/model/deployment/config/packages
          data-location: ${{ env.mdr-config-packages-json-path }}

      - name: '${{ github.repository }}: Get repository refs from config/versions.json'
        id: config-versions-refs
        run: |
          echo "spack-branch=$(jq --compact-output --raw-output '.spack' ${{ env.mdr-config-versions-json-path}})" >> $GITHUB_OUTPUT
          echo "access-spack-packages-ref=$(jq --compact-output --raw-output '."access-spack-packages"' ${{ env.mdr-config-versions-json-path }})" >> $GITHUB_OUTPUT

      - name: '${{ github.repository }}: Validate spack branch'
        id: spack-branch-check
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack
          ref: releases/v${{ steps.config-versions-refs.outputs.spack-branch }}

      - name: '${{ github.repository }}: Get access-spack-packages SHA'
        id: access-spack-packages-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/access-spack-packages
          ref: ${{ steps.config-versions-refs.outputs.access-spack-packages-ref }}

      # Validate the build-cd repository's config/settings.json for the deployment target
      - name: 'build-cd: Checkout build-cd Config'
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd
          path: build-cd

      - name: 'build-cd: Validate config/settings.json'
        id: settings
        uses: access-nri/build-cd/.github/actions/validate-deployment-settings@v8
        with:
          settings-path: ${{ env.build-cd-config-settings-json-path }}
          target: ${{ inputs.deployment-target }}

      - name: 'build-cd: Get repository refs from config/settings.json'
        id: config-settings-refs
        run: |
          refs_for_deployment=$(jq \
              --arg spack_version "${{ steps.config-versions-refs.outputs.spack-branch }}" \
              '.deployment.${{ inputs.deployment-target }}.${{ inputs.deployment-type }}[$spack_version]' \
              ${{ env.build-cd-config-settings-json-path }}
          )

          echo "$refs_for_deployment"

          echo "spack-ref=$(jq --compact-output --raw-output '.spack' <<< "$refs_for_deployment")" >> $GITHUB_OUTPUT
          echo "spack-config-ref=$(jq --compact-output --raw-output '."spack-config"' <<< "$refs_for_deployment")" >> $GITHUB_OUTPUT
          echo "builtin-spack-packages-ref=$(jq --compact-output --raw-output '."builtin-spack-packages"' <<< "$refs_for_deployment")" >> $GITHUB_OUTPUT

      - name: 'build-cd: Get spack SHA'
        id: spack-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack
          ref: ${{ steps.config-settings-refs.outputs.spack-ref }}

      - name: 'build-cd: Get spack-config SHA'
        id: spack-config-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: ACCESS-NRI/spack-config
          ref: ${{ steps.config-settings-refs.outputs.spack-config-ref }}

      - name: 'build-cd: Get builtin spack-packages SHA'
        id: builtin-spack-packages-sha
        uses: access-nri/actions/.github/actions/get-git-ref-info@main
        with:
          repository: spack/spack-packages
          ref: ${{ steps.config-settings-refs.outputs.builtin-spack-packages-ref }}

  check-spack-yaml:
    name: '${{ inputs.deployment-target }}: Check Spack Manifest'
    runs-on: ubuntu-latest
    env:
      # Note: since this is a string representation of a boolean, it must be compared as a string.
      # Yes, github.event.issue.draft refers to the pull request if the comment is made on a pull request!
      IS_NOT_DRAFT: ${{ (github.event_name == 'pull_request' && !github.event.pull_request.draft) || (github.event_name == 'issue_comment' && !github.event.issue.draft) }}
    permissions:
      pull-requests: write
    outputs:
      # Release version of the deployment. Inferred if not given in inputs.deployment-version
      release: ${{ steps.current.outputs.deployment-version }}
      # Spack env name in form <model>-<version>
      spack-env-name: ${{ steps.get-env-name.outputs.env-name }}
    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 0
          ref: ${{ inputs.deployment-ref }}

      - name: Validate ACCESS-NRI spack manifest restrictions
        if: env.IS_NOT_DRAFT == 'true' || inputs.deployment-type == 'Release'
        uses: access-nri/schema/.github/actions/validate-with-schema@main
        with:
          schema-version: ${{ inputs.spack-manifest-schema-version }}
          schema-location: ${{ inputs.spack-manifest-schema-path }}
          data-location: ${{ inputs.spack-manifest-path }}

      - name: Get current (${{ inputs.deployment-ref }}) root spec version
        id: current
        uses: access-nri/build-cd/.github/actions/get-spack-manifest@v8
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Checkout base (${{ inputs.prerelease-compare-ref }}) spack manifest
        if: inputs.deployment-type != 'Release'
        continue-on-error: true
        id: checkout-base-spack
        run: |
          git checkout ${{ inputs.prerelease-compare-ref }}

          if [ ! -f ${{ inputs.spack-manifest-path }} ]; then
              echo "::notice::There is no previous version of ${{ inputs.spack-manifest-path }} to check at ${{ inputs.prerelease-compare-ref }}, continuing..."
              exit 1
          fi

          # If the first commit in the repository is the template, there won't be anything defined in the speclist
          # So we should skip checking the version!
          if ! yq --exit-status '.spack.specs' ${{ inputs.spack-manifest-path }}; then
            echo "::notice::${{ inputs.spack-manifest-path }} at ${{ inputs.prerelease-compare-ref }} is a template, continuing..."
            exit 1
          fi

      - name: Get base root spec version
        id: base
        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure'
        uses: access-nri/build-cd/.github/actions/get-spack-manifest@v8
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Check Model Version Modified
        # We don't want to fire off model deployment version checks if the PR is never going to be merged.
        # We determine this by checking if either the pull request, or the pull request that a comment
        # belongs to, is drafted.
        if: inputs.deployment-type != 'Release' && steps.checkout-base-spack.outcome != 'failure' && env.IS_NOT_DRAFT == 'true'
        id: version-modified
        run: |
          if [[ "${{ steps.base.outputs.deployment-version }}" == "${{ steps.current.outputs.deployment-version }}" ]]; then
              echo "::warning::The version string in ${{ inputs.spack-manifest-path }} hasn't been modified in this PR, but needs to be before merging."
              exit 1
          fi

      - name: Same Model Version Failure Notifier
        if: failure() && steps.version-modified.outcome == 'failure'
        # TODO: We don't yet support bumping files outside of ./spack.yaml, so this is a temporary solution.
        env:
          BUMP_COMMENT_BODY: |-
            Alternatively, comment the following to have it updated and committed automatically:
              * `!bump major` for feature releases
              * `!bump minor` for bugfixes
        uses: access-nri/actions/.github/actions/pr-comment@main
        with:
          comment: |
              The model version in the `${{ inputs.spack-manifest-path }}` has not been updated.
              You can update it manually.
              ${{ inputs.spack-manifest-path != './spack.yaml' && env.BUMP_COMMENT_BODY || '' }}

      - name: Set Spack Env Name String
        id: get-env-name
        # replace occurences of '.' with '_' in environment name as spack doesn't support '.'. Ex: 'access-om2-v1.0.0' -> 'access-om2-v1_0_0'.
        run: echo "env-name=$(echo '${{ inputs.expected-root-spec-name }}-${{ inputs.deployment-version }}' | tr '.' '_')" >> $GITHUB_OUTPUT

  deployment:
    name: ${{ inputs.deployment-target }}
    needs:
      - check-config  # Verify configuration information is correct
      - check-spack-yaml  # Verify spack manifest information is correct
    uses: access-nri/build-cd/.github/workflows/deploy-2-start.yml@v8
    with:
      ref: ${{ inputs.deployment-ref }}
      version: ${{ inputs.deployment-version }}
      env-name: ${{ needs.check-spack-yaml.outputs.spack-env-name }}
      deployment-target: ${{ inputs.deployment-target }}
      deployment-type: ${{ inputs.deployment-type }}
      expected-root-spec-name: ${{ inputs.expected-root-spec-name }}
      spack-manifest-path: ${{ inputs.spack-manifest-path }}
    secrets: inherit

  outputs-upload:
    name: '${{ inputs.deployment-target }}:Outputs Upload'
    # Creates a JSON artifact with information on the deployment created during this run.
    # In workflows that call this as a matrix, one must do a deep merge with all files generated from the matrix,
    # using the outputs.general-outputs-artifact-name artifact as part of the workflow run.
    if: always()
    # always, because we might want to interrogate some of the information even in a failed deployment.
    needs:
      - check-config
      - check-spack-yaml
      - deployment
    runs-on: ubuntu-latest
    env:
      UPLOAD_FILE_NAME: deploy-${{ inputs.expected-root-spec-name }}-outputs.${{ inputs.deployment-target }}
    outputs:
      general-artifact-name: deploy-${{ inputs.expected-root-spec-name }}-outputs.*
    steps:
      - name: Create outputs file
        # See the on.workflow_call.outputs section for details on the info created.
        run: |
          jq --null-input '{
            model_name: "${{ github.event.repository.name }}",
            model_deployment_repository: "${{ github.event.repository.html_url }}",
            model_deployment_repository_spack_manifest_path: "${{ inputs.spack-manifest-path }}",
            spack_version: "${{ needs.check-config.outputs.spack-version }}",
            spack_git_hash: "${{ needs.check-config.outputs.spack-git-hash }}",
            spack_config_version: "${{ needs.check-config.outputs.spack-config-version }}",
            spack_config_git_hash: "${{ needs.check-config.outputs.spack-config-git-hash }}",
            builtin_spack_packages_version: "${{ needs.check-config.outputs.builtin-spack-packages-version }}",
            builtin_spack_packages_git_hash: "${{ needs.check-config.outputs.builtin-spack-packages-git-hash }}",
            access_spack_packages_version: "${{ needs.check-config.outputs.access-spack-packages-version }}",
            access_spack_packages_git_hash: "${{ needs.check-config.outputs.access-spack-packages-git-hash }}",
            ci_configuration_check_failure: ${{ needs.check-config.outputs.config-settings-failures != '' }},
            release_deployment_version: "${{ needs.check-spack-yaml.outputs.release }}",
            spack_environment_name: "${{ needs.check-spack-yaml.outputs.spack-env-name }}",
            root_spec_pkg_hash: "${{ needs.deployment.outputs.root-spec-pkg-hash }}",
            deployment_result: "${{ needs.deployment.result }}",
            deployment_modules_location: "${{ needs.deployment.outputs.modules-location }}",
            deployment_spack_location: "${{ needs.deployment.outputs.spack-location }}"
          }' > ./${{ env.UPLOAD_FILE_NAME }}

      - name: Upload
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.UPLOAD_FILE_NAME }}
          path: ./${{ env.UPLOAD_FILE_NAME }}
          if-no-files-found: error
