name: Deploy Start
on:
  workflow_call:
    inputs:
      ref:
        type: string
        required: true
        description: The git commit-ish ref where the spack manifest is located
      version:
        type: string
        required: true
        description: The version for the model being deployed
      env-name:
        type: string
        required: true
        description: The spack-env-compliant environment name for the model
      deployment-target:
        type: string
        required: true
        description: |
          The GitHub Environment, minus a Type.
          Combined with inputs.deployment-type to create the GitHub Environment name.
      deployment-type:
        type: string
        required: true
        description: |
          The type of deployment.
          Can be one of: Release, Prerelease.
          Combined with inputs.deployment-target to create the GitHub Environment name.
      expected-root-spec-name:
        type: string
        required: true
        description: |
          The expected root spec name that is defined at the repository level.
          May be different from the actual root spec name in the spack manifest.
      spack-manifest-path:
        type: string
        required: true
        description: The path to the spack manifest file, relative to the model deployment repository.
    outputs:
      root-spec-pkg-hash:
        value: ${{ jobs.deploy-to-environment.outputs.root-spec-pkg-hash }}
        description: The spack package long hash of the installed root spec
      modules-location:
        value: ${{ jobs.deploy-to-environment.outputs.modules-location }}
        description: The location of the modules directory on the deployment environment
      spack-location:
        value: ${{ jobs.deploy-to-environment.outputs.spack-location }}
        description: The location of the spack directory on the deployment environment
      general-metadata-artifact-glob:
        value: ${{ jobs.deploy-to-environment.outputs.metadata-artifact-name }}
        description: |
          General pattern for the artifact that contains the deployment metadata files for this invocation of the job.
          These files are of the form deploy-metadata.{{inputs.deployment-target}}
env:
  METADATA_PATH: /opt/metadata
  ARTIFACT_NAME: deploy-${{ inputs.expected-root-spec-name }}-metadata.${{ inputs.deployment-target }}
jobs:
  deploy-to-environment:
    name: Deploy to ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
    outputs:
      packages-version: ${{ steps.versions.outputs.packages }}
      config-version: ${{ steps.versions.outputs.config }}
      spack-location: ${{ steps.location.outputs.spack }}
      modules-location: ${{ steps.location.outputs.modules }}
      root-spec-pkg-hash: ${{ steps.metadata.outputs.root-spec-pkg-hash }}
      metadata-artifact-name: ${{ env.ARTIFACT_NAME }}
    steps:
      - name: Checkout ${{ github.repository }}
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Checkout build-cd
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd
          path: cd

      - name: Get Versions From config/versions.json
        id: versions
        run: |
          echo "spack=$(jq --compact-output --raw-output '.spack' ./config/versions.json)" >> $GITHUB_OUTPUT
          echo "packages=$(jq --compact-output --raw-output '."spack-packages"' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Get ${{ inputs.deployment-target }} ${{ inputs.deployment-type }} Remote Paths
        id: path
        uses: access-nri/build-cd/.github/actions/get-deploy-paths@v5
        with:
          spack-installs-root-path: ${{ vars.SPACK_INSTALLS_ROOT_LOCATION }}
          spack-version: ${{ steps.versions.outputs.spack }}
          deployment-environment: ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
          spack-environment: ${{ inputs.env-name }}

      - name: Get manifest info
        id: manifest
        uses: access-nri/build-cd/.github/actions/get-spack-root-spec@v5
        with:
          spack-manifest-path: ${{ inputs.spack-manifest-path }}

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Setup Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.11'
          cache: 'pip'

      - name: Install Injection Requirements
        working-directory: cd
        run: python -m pip install -r scripts/spack_manifest/injection/requirements.txt

      - name: Spack Manifest - Projection Injection
        # Injects relevant projections into the spack manifest so users don't have to
        # Note the cd prefix to the module name, as this is the path we cloned build-cd into
        run: |
          python -m cd.scripts.spack_manifest.injection.projections \
            --manifest ${{ inputs.spack-manifest-path }} \
            --root-spec ${{ steps.manifest.outputs.root-spec-name }} \
            --packages "${{ vars.BUILD_DB_PACKAGES }}" \
            --output ${{ inputs.spack-manifest-path }}

      - name: Spack Manifest - Prerelease Injection
        if: inputs.deployment-type == 'Prerelease'
        # Modifies the name of the prerelease modulefile to the pr<number>-<deployment number>` style.
        # Also removes the `@git.VERSION` specifier for Prereleases as it is a tag that doesn't yet exist.
        # Also adds a repos section that points to the prereleases specific spack-packages repo.
        # Note the cd prefix to the module name, as this is the path we cloned build-cd into
        run: |
          python -m cd.scripts.spack_manifest.injection.prerelease \
            --manifest ${{ inputs.spack-manifest-path }} \
            --root-spec ${{ steps.manifest.outputs.root-spec-name }} \
            --spack-packages-path ${{ steps.path.outputs.spack-packages }} \
            --output ${{ inputs.spack-manifest-path }}

      - name: Copy ${{ inputs.spack-manifest-path }}
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            ${{ inputs.spack-manifest-path }} \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_YAML_LOCATION }}/${{ inputs.expected-root-spec-name }}-${{ github.run_id }}.spack.yaml

      - name: Fetch git sources for packages to build
        # Workaround for ACCESS-NRI/spack#2.
        # TODO: Remove once underlying spack issue is fixed
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'

          if [ ! -d "${{ steps.path.outputs.root }}/git_repos" ]; then
            echo "::warning::Unable to find git_repos folder under ${{ steps.path.outputs.root }} - spack will attempt fetch instead"
            exit 0
          fi

          cd "${{ steps.path.outputs.root }}/git_repos" || exit 0

          for package_repo in *; do
            git -C "./$package_repo" fetch --verbose --update-head-ok origin "+refs/heads/*:refs/heads/*"
          done
          EOT

      - name: Update spack-packages repository
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Check that a suitable spack-packages location exists
          if [ ! -d '${{ steps.path.outputs.spack-packages-root }}' ]; then
            echo '::error::spack-packages does not exist in ${{ steps.path.outputs.root }} for ${{ inputs.deployment-target }} ${{ inputs.deployment-type}}'
            exit 1
          fi

          # In the case of a Prerelease, we need to create a new instance of spack-packages per commit, so there is no concurrent access problems.
          if [ ! -d '${{ steps.path.outputs.spack-packages }}' ]; then
            echo 'Creating spack-packages instance for ${{ inputs.env-name }} under ${{ steps.path.outputs.spack-packages }}'
            mkdir -p ${{ steps.path.outputs.spack-packages }}
            git clone https://github.com/ACCESS-NRI/spack-packages.git '${{ steps.path.outputs.spack-packages }}'
          fi

          cd ${{ steps.path.outputs.spack-packages }} || exit 1

          git fetch --all --tags

          if git ls-remote --exit-code --heads origin ${{ steps.versions.outputs.packages }}; then  # If the ref is a branch
            echo "Checking out the branch at the latest commit"
            git checkout -B ${{ steps.versions.outputs.packages }} origin/${{ steps.versions.outputs.packages }}
          else  # checkout the tag/commit
            echo "Checking out the tag/commit"
            git checkout ${{ steps.versions.outputs.packages }}
          fi
          EOT

      - name: Deploy to ${{ inputs.deployment-target }} ${{ inputs.deployment-type }}
        id: deploy
        # ssh into deployment environment, create and activate the env, install the spack manifest.
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Check that a suitable deployment location exists
          if [ ! -d "${{ steps.path.outputs.root }}" ]; then
            echo '::error::A deployment of spack does not exist in ${{ steps.path.outputs.root }} for ${{ inputs.deployment-target }} ${{ inputs.deployment-type}}'
            exit 1
          fi

          # Export vars.DEPLOYMENT_TARGET
          export DEPLOYMENT_TARGET="${{ vars.DEPLOYMENT_TARGET }}"
          echo "DEPLOYMENT_TARGET exported as $DEPLOYMENT_TARGET"

          # Enable spack
          . ${{ steps.path.outputs.spack-config }}/spack-enable.bash

          # Create environment and build model
          spack env create ${{ inputs.env-name }} ${{ vars.SPACK_YAML_LOCATION }}/${{ inputs.expected-root-spec-name }}-${{ github.run_id }}.spack.yaml
          spack env activate ${{ inputs.env-name }}
          spack --debug install --fail-fast --fresh ${{ vars.SPACK_INSTALL_ADDITIONAL_ARGS }} || exit $?
          spack module tcl refresh -y

      - name: Move spack logs
        if: always() && (steps.deploy.outcome == 'success' || steps.deploy.outcome == 'failure')
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          find . -maxdepth 1 -regex './spack-cc-.+' -exec mv {} ${{ steps.path.outputs.root }}/logs \;
          EOT

      - name: Export deployment target locations
        id: location
        run: |
          echo "spack=${{ steps.path.outputs.spack }}" >> $GITHUB_OUTPUT
          echo "modules=${{ vars.DEPLOYED_MODULES_DIR }}" >> $GITHUB_OUTPUT

      - name: Get metadata from ${{ inputs.deployment-target }} ${{ inputs.deployment-type}}
        id: metadata
        # Get the metadata from the spack environment regarding build database packages
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Export vars.DEPLOYMENT_TARGET
          export DEPLOYMENT_TARGET="${{ vars.DEPLOYMENT_TARGET }}"
          echo "DEPLOYMENT_TARGET exported as $DEPLOYMENT_TARGET"

          . ${{ steps.path.outputs.spack-config }}/spack-enable.bash
          spack env activate ${{ inputs.env-name }}

          spack find --paths > ${{ steps.path.outputs.spack-environment }}/spack.location

          # output the root-spec-pkg-hash into a file that is accessible outside the ssh session
          echo "root-spec-pkg-hash=$(spack find --format '{hash}' ${{ inputs.expected-root-spec-name }})" > ${{ steps.path.outputs.spack-environment }}/root-spec-pkg-hash.${{ github.run_id }}

          # Get the information associated with the packages for the build database
          jq -n '[]' > ${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json

          for pkg in ${{ vars.BUILD_DB_PACKAGES }}; do
            hash=$(spack find --format '{hash}' $pkg)
            version=$(spack find --format '{version}' $pkg)
            location=$(spack find --format '{prefix}' $pkg)
            pkg_repo_url=$(spack python -c "import spack.spec; print(spack.spec.Spec('$pkg').package_class.git)")

            # We need to create a tmp output file as jq doesn't support in-place read/write
            jq \
              --arg p "$pkg" \
              --arg v "$version" \
              --arg h "$hash" \
              --arg l "$location" \
              --arg r "$pkg_repo_url" \
              '. += [{"name": $p, "version": $v, "hash": $h, "location": $l, "url": $r}]' \
              ${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json > ${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json.tmp

            mv -f ${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json.tmp ${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json
          done

          spack env deactivate
          EOT

          # Output root spec package hash from ssh session
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            --remove-source-files \
            ${{ secrets.USER }}@${{ secrets.HOST }}:${{ steps.path.outputs.spack-environment }}/root-spec-pkg-hash.${{ github.run_id }} \
            ./root-spec-pkg-hash.${{ github.run_id }}

          echo "$(cat ./root-spec-pkg-hash.${{ github.run_id }})" >> $GITHUB_OUTPUT
          rm ./root-spec-pkg-hash.${{ github.run_id }}

      - name: Tar spack environment metadata
        if: inputs.deployment-type == 'Prerelease'
        run: |
          ssh ${{ secrets.USER }}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          if [ -d "${{ steps.path.outputs.spack-environment }}/.spack-env" ]; then
            tar --remove-files --create --file ${{ steps.path.outputs.spack-environment }}/.spack-env.tar ${{ steps.path.outputs.spack-environment }}/.spack-env
          else
            echo "::warning::No .spack-env directory found in ${{ steps.path.outputs.spack-environment }}, not tarring. There may be an issue with the environment."
          fi
          EOT

      # Release
      - name: Get Release Metadata
        # Copy both the spack.* files and the build-db-pkgs.json file to the artifact
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            '${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ steps.path.outputs.spack-environment }}/spack.*' \
            '${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ steps.path.outputs.spack-environment }}/build-db-pkgs.json' \
            ./${{ env.ARTIFACT_NAME }}

          # Rename the files to include the deployment environment
          cd ./${{ env.ARTIFACT_NAME }}
          for file in *; do
            mv "$file" "${{ inputs.deployment-target }}.$file"
          done
          cd -

      - name: Upload Metadata Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ env.ARTIFACT_NAME }}
          path: ./${{ env.ARTIFACT_NAME }}/*
