name: Deploy Start
concurrency: ${{ inputs.deployment-environment }}
on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
        description: The type of deployment - either 'release' or 'prerelease'
      model:
        type: string
        required: true
        description: The model to deploy
      ref:
        type: string
        required: true
        description: The git commit-ish ref where the `spack.yaml` is located
      version:
        type: string
        required: true
        description: The version for the model being deployed
      env-name:
        type: string
        required: true
        description: The spack-env-compliant environment name for the model
      deployment-environment:
        type: string
        required: true
        description: The GitHub deployment environment name
      root-sbd:
        type: string
        required: false
        default: ${{ inputs.model }}
        description: The root SBD that is being used as the modulefile name
env:
  SPACK_YAML_MODULEFILE_PROJECTION_YQ: .spack.modules.default.tcl.projections.${{ inputs.root-sbd }}
jobs:
  deploy-to-environment:
    name: Deploy to ${{ inputs.deployment-environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    steps:
      # Deployment
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Get packages and config versions
        id: versions
        run: |
          echo "packages=$(jq --compact-output --raw-output '."spack-packages"' ./config/versions.json)" >> $GITHUB_OUTPUT
          echo "config=$(jq --compact-output --raw-output '."spack-config"' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Prerelease Modulefile Name
        if: inputs.type == 'prerelease'
        # Modifies the name of the prerelease modulefile to the
        # `pr<number>-<commit>` style. For example, `access-om3/pr12-2`
        run: |
          yq -i '${{ env.SPACK_YAML_MODULEFILE_PROJECTION_YQ }} = "{name}/${{ inputs.version }}"' spack.yaml
          echo "::notice::Prerelease accessible as module `${{ inputs.model}}/${{ inputs.version }}`"

      - name: Copy spack.yaml
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            spack.yaml \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_YAML_LOCATION }}

      - name: Deploy to ${{ inputs.deployment-environment }}
        # ssh into deployment environment, create and activate the env, install the spack.yaml.
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Update spack-packages/config
          git -C ${{ vars.SPACK_PACKAGES_LOCATION }} fetch
          git -C ${{ vars.SPACK_PACKAGES_LOCATION }} checkout --force ${{ steps.versions.outputs.packages }}
          git -C ${{ vars.SPACK_CONFIG_LOCATION }} fetch
          git -C ${{ vars.SPACK_CONFIG_LOCATION }} checkout --force ${{ steps.versions.outputs.config }}

          # Enable spack
          . ${{ vars.SPACK_CONFIG_LOCATION }}/spack-enable.bash

          # Create environment and build model
          spack env create ${{ inputs.env-name }} ${{ vars.SPACK_YAML_LOCATION }}/spack.yaml
          spack env activate ${{ inputs.env-name }}
          spack --debug install --fresh --jobs 4 || exit $?
          spack module tcl refresh --delete-tree -y

          # Obtain metadata
          spack find --paths > ${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.location
          spack find --format '{name}@{version} {prefix}' | jq --raw-input --null-input '[inputs | split(" ") | {(.[0]):(.[1])}] | add' > ${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.location.json

          spack env deactivate
          echo "$(date): Deployed ${{ inputs.model }} ${{ inputs.version }} with spack-packages ${{ steps.versions.outputs.packages }}, spack-config ${{ steps.versions.outputs.config }}" >> ${{ vars.SPACK_RELEASE_LOCATION }}/release.log
          EOT

      # Release
      - name: Get Release Metadata
        if: inputs.type == 'release'
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            '${{ secrets.USER}}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.*' \
            ./${{ inputs.env-name }}

      - name: Create Release
        if: inputs.type == 'release'
        uses: softprops/action-gh-release@v0.1.15
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.model}} ${{ inputs.version }}
          body: |
            This release of ${{ inputs.model }} ${{ inputs.version }} uses [spack-packages ${{ steps.versions.outputs.packages }}](https://github.com/ACCESS-NRI/spack-packages/releases/tag/${{ steps.versions.outputs.packages }}) and [spack-config ${{ steps.versions.outputs.config }}](https://github.com/ACCESS-NRI/spack-config/releases/tag/${{ steps.versions.outputs.config }}).
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ./${{ inputs.env-name }}/spack.yaml
            ./${{ inputs.env-name }}/spack.lock
            ./${{ inputs.env-name }}/spack.location
            ./${{ inputs.env-name }}/spack.location.json
