name: Deploy Start
concurrency: ${{ inputs.deployment-environment }}
on:
  workflow_call:
    inputs:
      type:
        type: string
        required: true
        description: The type of deployment - either 'release' or 'prerelease'
      model:
        type: string
        required: true
        description: The model to deploy
      ref:
        type: string
        required: true
        description: The git commit-ish ref where the `spack.yaml` is located
      version:
        type: string
        required: true
        description: The version for the model being deployed
      env-name:
        type: string
        required: true
        description: The spack-env-compliant environment name for the model
      deployment-environment:
        type: string
        required: true
        description: The GitHub deployment environment name
      root-sbd:
        type: string
        required: false
        default: ${{ inputs.model }}
        description: The root SBD that is being used as the modulefile name
env:
  SPACK_YAML_MODULEFILE_PROJECTION_YQ: .spack.modules.default.tcl.projections.${{ inputs.root-sbd }}
  METADATA_PATH: /opt/metadata
jobs:
  deploy-to-environment:
    name: Deploy to ${{ inputs.deployment-environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    outputs:
      packages-version: ${{ steps.versions.outputs.packages }}
      config-version: ${{ steps.versions.outputs.config }}
    steps:
      # Deployment
      - uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Get packages and config versions
        id: versions
        run: |
          echo "packages=$(jq --compact-output --raw-output '."spack-packages"' ./config/versions.json)" >> $GITHUB_OUTPUT
          echo "config=$(jq --compact-output --raw-output '."spack-config"' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Prerelease Modulefile Name
        if: inputs.type == 'prerelease'
        # Modifies the name of the prerelease modulefile to the
        # `pr<number>-<commit>` style. For example, `access-om3/pr12-2`
        run: |
          yq -i '${{ env.SPACK_YAML_MODULEFILE_PROJECTION_YQ }} = "{name}/${{ inputs.version }}"' spack.yaml
          echo "::notice::Prerelease accessible as module `${{ inputs.model}}/${{ inputs.version }}`"

      - name: Copy spack.yaml
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            spack.yaml \
            ${{ secrets.USER }}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_YAML_LOCATION }}

      - name: Deploy to ${{ inputs.deployment-environment }}
        # ssh into deployment environment, create and activate the env, install the spack.yaml.
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          # Update spack-packages/config
          git -C ${{ vars.SPACK_PACKAGES_LOCATION }} fetch
          git -C ${{ vars.SPACK_PACKAGES_LOCATION }} checkout --force ${{ steps.versions.outputs.packages }}
          git -C ${{ vars.SPACK_CONFIG_LOCATION }} fetch
          git -C ${{ vars.SPACK_CONFIG_LOCATION }} checkout --force ${{ steps.versions.outputs.config }}

          # Enable spack
          . ${{ vars.SPACK_CONFIG_LOCATION }}/spack-enable.bash

          # Create environment and build model
          spack env create ${{ inputs.env-name }} ${{ vars.SPACK_YAML_LOCATION }}/spack.yaml
          spack env activate ${{ inputs.env-name }}
          spack --debug install --fresh ${{ vars.SPACK_INSTALL_PARALLEL_JOBS }} || exit $?
          spack module tcl refresh -y

          # Obtain metadata
          spack find --paths > ${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.location
          spack find --format '{hash} {prefix}' | jq --raw-input --null-input '[inputs | split(" ") | {(.[0]): (.[1])}] | add' > ${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.location.json

          spack env deactivate
          echo "$(date): Deployed ${{ inputs.model }} ${{ inputs.version }} with spack-packages ${{ steps.versions.outputs.packages }}, spack-config ${{ steps.versions.outputs.config }}" >> ${{ vars.SPACK_RELEASE_LOCATION }}/release.log
          EOT

      # Release
      - name: Get Release Metadata
        run: |
          rsync -e 'ssh -i ${{ steps.ssh.outputs.private-key-path }}' \
            '${{ secrets.USER}}@${{ secrets.HOST_DATA }}:${{ vars.SPACK_LOCATION }}/var/spack/environments/${{ inputs.env-name }}/spack.*' \
            ./${{ inputs.env-name }}

      - name: Upload Metadata Artifact
        uses: actions/upload-artifact@v4
        with:
          name: ${{ inputs.env-name }}
          path: ./${{ inputs.env-name }}/*
          overwrite: true

  release:
    name: Create Release
    if: inputs.type == 'release'
    needs:
      - deploy-to-environment
    runs-on: ubuntu-latest
    outputs:
      url: ${{ steps.release.outputs.url }}
      created-at: ${{ steps.metadata.outputs.created-at }}
    steps:
      - uses: actions/checkout@v4

      - name: Download Metadata Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.env-name }}
          path: ${{ env.METADATA_PATH }}

      - name: Create Release
        id: release
        uses: softprops/action-gh-release@69320dbe05506a9a39fc8ae11030b214ec2d1f87  # v2.0.5
        with:
          tag_name: ${{ inputs.version }}
          name: ${{ inputs.model}} ${{ inputs.version }}
          body: |
            This release of ${{ inputs.model }} ${{ inputs.version }} uses [spack-packages ${{ needs.deploy-to-environment.outputs.packages-version }}](https://github.com/ACCESS-NRI/spack-packages/releases/tag/${{ needs.deploy-to-environment.outputs.packages-version }}) and [spack-config ${{ needs.deploy-to-environment.outputs.config-version }}](https://github.com/ACCESS-NRI/spack-config/releases/tag/${{ needs.deploy-to-environment.outputs.config-version }}).
          generate_release_notes: true
          fail_on_unmatched_files: true
          files: |
            ${{ env.METADATA_PATH }}/spack.yaml
            ${{ env.METADATA_PATH }}/spack.lock
            ${{ env.METADATA_PATH }}/spack.location
            ${{ env.METADATA_PATH }}/spack.location.json

      - name: Release Metadata
        id: metadata
        env:
          GH_TOKEN: ${{ github.token }}
        run: echo "created-at=$(gh release view --json createdAt --jq '.createdAt')" >> $GITHUB_OUTPUT

  build-db:
    name: Build DB Metadata Upload
    if: inputs.type == 'release'
    needs:
      - release
    runs-on: ubuntu-latest
    steps:
      - name: Download Metadata Artifact
        uses: actions/download-artifact@v4
        with:
          name: ${{ inputs.env-name }}
          path: ${{ env.METADATA_PATH }}

      - name: Checkout Upload Script
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd

      - name: Setup Python
        uses: actions/setup-python@v5
        with:
          python-version: "3.10"
          cache: pip

      - name: Install Build Metadata Script Requirements
        run: pip install -r tools/release_provenance/requirements.txt

      - name: Upload Build Metadata
        env:
          BUILD_DB_CONNECTION_STR: ${{ secrets.BUILD_DB_CONNECTION_STR }}
          OUTPUT_PATH: ./metadata_output
        run: |
          ./scripts/generate-build-metadata.bash ${{ needs.release.outputs.url }} ${{ needs.release.outputs.created-at }} ${{ env.METADATA_PATH }} ${{ env.OUTPUT_PATH }} ${{ inputs.root-sbd }} ${{ vars.BUILD_DB_PACKAGES }}

          echo "Attempting upload of build_metadata.json"
          python ./tools/release_provenance/save_release.py "${{ env.OUTPUT_PATH }}/build_metadata.json"
