name: Undeployment Start
on:
  workflow_call:
    inputs:
      env-name:
        type: string
        required: true
        description: The spack-env-compliant model name to remove
      deployment-environment:
        type: string
        required: true
        description: The GitHub deployment environment name
jobs:
  undeploy-from-environment:
    name: Undeploy ${{ inputs.env-name }} from ${{ inputs.deployment-environment }}
    runs-on: ubuntu-latest
    environment: ${{ inputs.deployment-environment }}
    steps:
      - uses: actions/checkout@v4

      - name: Get Versions From config/versions.json
        id: versions
        run: |
          echo "spack=$(jq --compact-output --raw-output '.spack' ./config/versions.json)" >> $GITHUB_OUTPUT
          echo "config=$(jq --compact-output --raw-output '."spack-config"' ./config/versions.json)" >> $GITHUB_OUTPUT

      - name: Get ${{ inputs.deployment-environment }} Remote Paths
        id: path
        uses: access-nri/build-cd/.github/actions/get-deploy-paths@main
        with:
          spack-installs-root-path: ${{ vars.SPACK_INSTALLS_ROOT_LOCATION }}
          spack-version: ${{ steps.versions.outputs.spack }}
          deployment-environment: ${{ inputs.deployment-environment }}

      - name: Setup SSH
        id: ssh
        uses: access-nri/actions/.github/actions/setup-ssh@main
        with:
          private-key: ${{ secrets.SSH_KEY }}
          hosts: |
            ${{ secrets.HOST }}
            ${{ secrets.HOST_DATA }}

      - name: Undeploy
        # ssh into deployment environment, create and activate the env, remove all the unneeded environments
        id: undeploy
        run: |
          ssh ${{ secrets.USER}}@${{ secrets.HOST }} -i ${{ steps.ssh.outputs.private-key-path }} /bin/bash <<'EOT'
          . ${{ steps.path.outputs.spack-config }}/spack-enable.bash
          envs=$(find ${{ steps.path.outputs.spack }}/var/spack/environments -type d -name '${{ inputs.env-name }}' -printf '%f ')

          for env in $envs; do
            spack env activate $env
            spack uninstall --remove --dependents --yes-to-all --all
            spack env deactivate
            spack env rm $env --yes-to-all
          done
          spack gc --yes-to-all
          EOT

      - name: Undeploy Status Notifier
        if: always()
        run: |
          if [[ "${{ steps.undeploy.outcome }}" == "success" ]]; then
            echo "::notice::Deployment ${{ inputs.env-name }} was successfully removed from ${{ inputs.deployment-environment }}, found at ${{ steps.path.outputs.spack }}"
          else
            echo "::error::Deployment ${{ inputs.env-name }} couldn't be removed from ${{ inputs.deployment-environment}}, found at ${{ steps.path.outputs.spack }}. Please check manually."
          fi
