name: Undeployment Setup
on:
  workflow_call:
    inputs:
      version-pattern:
        type: string
        required: true
        description: A wildcard-supported string of spack environments to remove
jobs:
  get-prerelease-deployment-env:
    name: Get Prerelease Deployment Environment
    runs-on: ubuntu-latest
    outputs:
      deployment-environments: ${{ steps.get-deployment-environment.outputs.deployment-environments }}
    steps:
      - name: Checkout Config
        uses: actions/checkout@v4
        with:
          repository: access-nri/build-cd

      - name: Get Environments
        id: get-deployment-environment
        # Note: We run under the assumption that all Prerelease Environments have 'Prerelease'
        # appended to their GitHub Environment name, which is set out in our deployment template
        # https://github.com/ACCESS-NRI/model-deployment-template/blob/main/README.md?plain=1#L41
        run: echo "deployment-environments=$(jq --compact-output '.deployment | keys[] | "\(.) Prerelease"' ./config/settings.json)" >> $GITHUB_OUTPUT


  undeployment:
    name: Remove Deployment
    needs:
      - get-prerelease-deployment-env
    strategy:
      fail-fast: false
      matrix:
        deployment-environment: ${{ fromJson(needs.get-prerelease-deployment-env.outputs.deployment-environments) }}
    uses: access-nri/build-cd/.github/workflows/undeploy-2-start.yml@main
    with:
      deployment-environment: ${{ matrix.deployment-environment }}
      env-name: ${{ inputs.version-pattern }}
    secrets: inherit
